const ACCESS_TOKEN_NAME : string = "ACCESS";
const REFRESH_TOKEN__NAME :string = "REFRESH";
const USER_LOCALSTORAGE_DATA_NAME: string = "fasdsdgsd"

export {ACCESS_TOKEN_NAME, REFRESH_TOKEN__NAME, USER_LOCALSTORAGE_DATA_NAME}